#!/bin/bash

# Runs catkin_make with the correct whitelist entries.

# beagle = all packages for the beagle bone
# mm_p = Mouse Monitor for pc
# mm_b = Mouse Monitor for beagle bone
# mm_b_cross = Cross compile Mouse Monitor for beagle bone
# pc = All other pc packages

START_DIR=$PWD
BASEDIR=$(dirname $0)

cd $BASEDIR

if [ -z "$1" ]
then
        echo "Give packages to compile."
fi

if [ "$1" == "beagle" ]
then
	sudo ntpdate -b -s -u ntp.ubuntu.com pool.ntp.org
	catkin_make -DCATKIN_WHITELIST_PACKAGES="minotaur_common;robot_control;minotaur_maze"
elif [ "$1" == "mm_p" ]
then
	catkin_make -DCATKIN_WHITELIST_PACKAGES="mouse_monitor_beagle;mouse_monitor_pc"
elif [ "$1" == "mm_b" ]
then
	sudo ntpdate -b -s -u ntp.ubuntu.com pool.ntp.org
	catkin_make -DCATKIN_WHITELIST_PACKAGES="minotaur_common;mouse_monitor_beagle"
elif [ "$1" == "mm_b_cross" ]
then
	TOOLCHAIN_PATH = "../toolchain-BeagleBoneBlack.cmake"
	catkin_make -DCATKIN_WHITELIST_PACKAGES="minotaur_common;mouse_monitor_beagle" -DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_PATH
elif [ "$1" == "pc" ]
then
	catkin_make -DCATKIN_WHITELIST_PACKAGES="minotaur_common;minotaur_common_qt;pid_monitor;minotaur_maze"
elif [ "$1" == "maze" ]
then
	catkin_make -DCATKIN_WHITELIST_PACKAGES="minotaur_common;robot_control;minotaur_maze"
elif [ "$1" == "all" ]
then
	catkin_make -DCATKIN_WHITELIST_PACKAGES="minotaur_common;minotaur_common_qt;robot_control;pid_monitor;minotaur_maze;minotaur_map;map_monitor" -DUSE_MOUSE_SENSOR="TRUE" -DBUILD_TEST_FILES="TRUE"
elif [ "$1" == "doxy" ]
then
	cd doc
	doxygen Doxyfile
elif [ "$1" == "clean" ]
then
	rm -rf devel/ build/
fi

cd $START_DIR
