#!/bin/bash

# The following packages are available:

# mm_b = mouse_monitor_beagle
# mm_p = mouse_monitor_pc
# pm_p = pid_monitor_pc
# rc_b = robot_control_beagle
# map_p = map_monitor_pc
# mtel_p = minotaur_pc minotaurTeleop
# mbug_p = minotaur_pc buggyMinotaur
# mb_b = robot_control_beagle: Move base

BEAGLE_IP=141.37.31.129
PC_IP=141.37.31.80

if [ -z "$1" ]
then
	echo "Give package to start."
fi

source devel/setup.bash

if [ "$1" == "mm_b" ]
then
	export ROS_IP=$BEAGLE_IP
	export ROS_MASTER_URI=http://$PC_IP:11311
	roslaunch mouse_monitor_beagle mousemonitor.launch
elif [ "$1" == "mm_p" ]
then
	export ROS_IP=$PC_IP
	export ROS_MASTER_URI=http://$PC_IP:11311
	roslaunch mouse_monitor_pc mousemonitor.launch
elif [ "$1" == "pm_p" ]
then
	export ROS_IP=$PC_IP
	export ROS_MASTER_URI=http://$PC_IP:11311
	roslaunch pid_monitor pidcontrol.launch
elif [ "$1" == "rc_b" ]
then
	export ROS_IP=$BEAGLE_IP
	export ROS_MASTER_URI=http://$PC_IP:11311
	roslaunch robot_control control.launch
elif [ "$1" == "map_p" ]
then
	export ROS_IP=$PC_IP
	export ROS_MASTER_URI=http://$PC_IP:11311
	roslaunch map_monitor mapteleop.launch
elif [ "$1" == "mtel_p" ]
then
	export ROS_IP=$PC_IP
	export ROS_MASTER_URI=http://$PC_IP:11311
	roslaunch minotaur_pc teleop.launch
elif [ "$1" == "mbug_p" ]
then
        export ROS_IP=$PC_IP
        export ROS_MASTER_URI=http://$PC_IP:11311
        roslaunch minotaur_pc bug.launch
elif [ "$1" == "mb_b" ]
then
	export ROS_IP=$PC_IP
	export ROS_MASTER_URI=http://$PC_IP:11311
	roslaunch robot_control move_base.launch
elif [ "$1" == "joy_p" ]
then
	export ROS_IP=$PC_IP
        export ROS_MASTER_URI=http://$PC_IP:11311
	roslaunch minotaur_teleop joy_teleop.launch
fi
