#ifndef NXT_OPCODES_HPP
#define NXT_OPCODES_HPP

#define LEGO_VENDOR_ID 0x0694
#define NXT_PRODUCT_ID 0x0002

#define NXT_USB_OUT_ENDPOINT 0x01
#define NXT_USB_IN_ENDPOINT 0x82

#define NXT_MAX_FILE_NAME_LENGTH 20
#define NXT_MAX_MESSAGE_LENGTH 59

/* Motor Ports */
#define PORT_A 0x00
#define PORT_B 0x01
#define PORT_C 0x02
#define ALL_PORTS 0xFF

/* Sensor Ports */
#define PORT_1 0x00
#define PORT_2 0x01
#define PORT_3 0x02
#define PORT_4 0x03

/* Message Types */
#define DIRECT_CMD 0x00
#define SYSTEM_CMD 0x01
#define REPLY_TELEGRAM 0x02
#define DIRECT_CMD_NO_REPLY 0x80
#define SYSTEM_CMD_NO_REPLY 0x81

/* Commands */
#define CMD_START_PROGRAM 0x00
#define CMD_STOP_PROGRAM 0x01
#define CMD_PLAY_SOUND_FILE 0x02
#define CMD_PLAY_TONE 0x03
#define CMD_SET_OUTPUT_STATE 0x04
#define CMD_SET_INPUT_MODE 0x05
#define CMD_GET_OUTPUT_STATE 0x06
#define CMD_GET_INPUT_VALUES 0x07
#define CMD_RESET_INPUT_SCALED_VALUE 0x08
#define CMD_MESSAGE_WRITE 0x09
#define CMD_RESET_MOTOR_POSITION 0x0A
#define CMD_GET_BATTERY_LEVEL 0x0B
#define CMD_STOP_SOUND_PLAYBACK 0x0C
#define CMD_KEEP_ALIVE 0x0D
#define CMD_LSGETSTATUS 0x0E
#define CMD_LSWRITE 0x0F
#define CMD_LSREAD 0x10
#define CMD_GET_CURRENT_PROGRAM_NAME 0x11
#define CMD_MESSAGE_READ 0x13

/* Mailbox numbers */
#define MAILBOX1 0x01
#define MAILBOX2 0x02
#define MAILBOX3 0x03
#define MAILBOX4 0x04
#define MAILBOX5 0x05
#define MAILBOX6 0x06
#define MAILBOX7 0x07
#define MAILBOX8 0x08
#define MAILBOX9 0x09

/* Motor Modes */
#define MOTOR_MODE_COAST 0x00
#define MOTOR_MODE_ON 0x01
#define MOTOR_MODE_BRAKE 0x02
#define MOTOR_MODE_ON_BRAKE 0x03
#define MOTOR_MODE_REGULATED 0x04
#define MOTOR_MODE_REGULATED_ON 0x05
#define MOTOR_MODE_REGULATED_BRAKE_ON 0x07

/* Motor Regulation Modes */
#define REGULATION_MODE_NONE 0x00
#define REGULATION_MODE_SPEED 0x01
#define REGULATION_MODE_SYNCH 0x02

/* Motor Run States */
#define RUN_STATE_IDLE 0x00
#define RUN_STATE_RAMP_UP 0x10
#define RUN_STATE_RUNNING 0x20
#define RUN_STATE_RAMP_DOWN 0x40

/* Sensor Types */
#define SENSOR_TYPE_NO_SENSOR 0x00
#define SENSOR_TYPE_SWITCH 0x01
#define SENSOR_TYPE_TEMPERATURE 0x02
#define SENSOR_TYPE_REFLECTION 0x03
#define SENSOR_TYPE_ANGLE 0x04
#define SENSOR_TYPE_LIGHT_ACTIVE 0x05
#define SENSOR_TYPE_LIGHT_INACTIVE 0x06
#define SENSOR_TYPE_SOUND_DB 0x07
#define SENSOR_TYPE_SOUND_DBA 0x08
#define SENSOR_TYPE_CUSTOM 0x09
#define SENSOR_TYPE_LOWSPEED 0x0A
#define SENSOR_TYPE_LOWSPEED_9V 0x0B
#define SENSOR_TYPE_NO_OF_SENSOR_TYPES 0x0C

/* Sensor Modes */
#define SENSOR_MODE_RAW 0x00
#define SENSOR_MODE_BOOLEAN 0x20
#define SENSOR_MODE_TRANSITION_CNT 0x40
#define SENSOR_MODE_PERIOD_COUNTER 0x60
#define SENSOR_MODE_PCT_FULL_SCALE 0x80
#define SENSOR_MODE_CELSIUS 0xA0
#define SENSOR_MODE_FAHRENHEIT 0xC0
#define SENSOR_MODE_ANGLE_STEP 0xE0
#define SENSOR_MODE_SLOPE_MASK 0x1F
#define SENSOR_MODE_MASK 0xE0

/* LS Commands */
#define LS_ULTRASONIC_ADDRESS 0x02
#define LS_SET_ULTRASONIC_MODE 0x41
#define READ_ULTRASONIC_BYTE0 0x42

/* Ultrasonic modes */
#define ULTRASONIC_MODE_OFF 0x00
#define ULTRASONIC_MODE_SINGLESHOT 0x01
#define ULTRASONIC_MODE_CONTINUOUS 0x02

#endif